### ISSUE TITLE
Auth issue with Ubuntu 15.10 (PocketMine for 0.13.1)

### ISSUE THREAD

**Issue by SirAquarus** [Falkirks/BuyCraft#15]
Despite my many efforts to try, the plugin **will not** communicate with the BuyCraft system. I've tried everything including encasing the 'Secret' in speech marks (""). Please can you explain to me what I'm doing wrong.

(I am aware BuyCraft was experiencing problems, but these have now been fixed.)

**Comment by Falkirks** [comment]
Have you gotten it to authenticate on older PocketMine build? Could you try that now and see if the issue is specific to 0.13.1 or if it applies to every version? BuyCraft may have changed something on their end.

(They are rarely clear on when the problems have been fixed, their Twitter isn't always to be trusted.)

**Comment by isoz** [comment]
I'm getting authentication error.

**Comment by Falkirks** [comment]
#16 might fix this issue. I will test it and then tag a release for you.

**Comment by isoz** [comment]
Thanks man, very much appreciated, wasnt expecting you to reply any time soon, this is great.
Buycraft should really man up and start cashing in on mobile users.

**Comment by Falkirks** [comment]
Issue is fixed for me in #16. Release has been tagged and will be submitted for review on the forums.

**Comment by isoz** [comment]
it worked. Thank you!

**Comment by legoboy0215** [comment]
THANKS

**Comment by SirAquarus** [comment]
Thanks a bunch. Will test later.

**Comment by isoz** [comment]
Its not working again for me :(
